name: Publish npm

on:
  push:
    tags:
      - v/*

jobs:

  publish:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      contents: read
      id-token: write

    steps:

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2

      - name: Build
        run: deno task build-npm

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: v22
          registry-url: https://registry.npmjs.org/

      - name: Update npm
        run: npm install -g npm@11.5

      - name: Publish to npm (next)
        if: contains(github.ref_name, '-') == true
        run: npm publish --access=public --tag=next

      - name: Publish to npm (latest)
        if: contains(github.ref_name, '-') == false
        run: npm publish --access=public --tag=latest

